
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 16;
  public static final int LT = 21;
  public static final int ELSE = 3;
  public static final int PLUS = 14;
  public static final int RBRACE = 30;
  public static final int RPAREN = 28;
  public static final int INT = 6;
  public static final int LTE = 23;
  public static final int SEMI = 25;
  public static final int WHILE = 4;
  public static final int LOWER_THAN_ELSE = 31;
  public static final int RETURN = 5;
  public static final int IF = 2;
  public static final int LBRACE = 29;
  public static final int LPAREN = 27;
  public static final int GT = 22;
  public static final int GTE = 24;
  public static final int ID = 10;
  public static final int STRING_LITERAL = 13;
  public static final int COMMA = 26;
  public static final int FLOAT = 7;
  public static final int EOF = 0;
  public static final int DIV = 17;
  public static final int MINUS = 15;
  public static final int PRINT = 9;
  public static final int error = 1;
  public static final int EQ = 19;
  public static final int ASSIGN = 18;
  public static final int INTEGER_LITERAL = 11;
  public static final int FLOAT_LITERAL = 12;
  public static final int NEQ = 20;
  public static final int VOID = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "INT",
  "FLOAT",
  "VOID",
  "PRINT",
  "ID",
  "INTEGER_LITERAL",
  "FLOAT_LITERAL",
  "STRING_LITERAL",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "ASSIGN",
  "EQ",
  "NEQ",
  "LT",
  "GT",
  "LTE",
  "GTE",
  "SEMI",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LOWER_THAN_ELSE"
  };
}

